version: 2
jobs:
  build:
    working_directory: ~/gisida-react
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: yarn install
      - run: 
          name: Run tests
          command: npm run test
      - run: 
          name: Compile production build
          command: npm run build
 publish:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn install
      - run: yarn build
      - run: npm publish
workflows:
  version: 2
  tagged-build:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: /[0-9]+(\.[0-9]+)*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
  
